### ISSUE TITLE
'\data\Configuration\config.cfg not found

### ISSUE THREAD

**Issue by dslutej** [Lecrapouille/Ecstasy#2]
procedure sauvegarder();
var
   OutFile : file;
begin
   AssignFile(OutFile, GetCurrentDir + '\data\Configuration\config.cfg');
   Reset(OutFile);
   blockWrite(OutFile, params, 1);
   CloseFile(OutFile);
end;

**Comment by Lecrapouille** [comment]
Hi @dslutej, thanks for your support :) It's because I made a mistake : I included this file extension in the gitignore because I did not wanted to add the one made by Borland IDE. I'll add it while from my memory It was useful for the video in the introduction that we never made finally :)

**Comment by Lecrapouille** [comment]
@dslutej Tell me if it's ok now :)
