### ISSUE TITLE
Delphi 10.2.1: Failed to open DIB file R x2

### ISSUE THREAD

**Issue by dslutej** [Lecrapouille/Ecstasy#3]
When starting, this is reported twice.

**Comment by Lecrapouille** [comment]
I have no idea of what this error can come from ? Maybe related to BMP old file format ? Can you tell me more ?
PS: I have it with your exe but in my case it's name "DIB file C" (not R)

**Comment by Lecrapouille** [comment]
Ok I know which texture is faulty: the two ones I added recently: cross.jpg and road.jpg. I think the bug comes from the jpg loader. So I convert them into bmp files. And this also fix the blinking effect with the fake white horizontal line.
